config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products
  resources :order_items
  resource :carts, only: [:show]
  resources :posts
  get '/receipt' => "pages#receipt"
  #get '/supplier' => "pages#supplier"
  get '/about_us' => "pages#aboutus"
  get '/contact_us' => "pages#contactus"
  get '/logout' => "sessions#logout"

  root "admin#index"


  # get 'admin/index'
  post 'sessions/create'
  get 'users/new'

get '/create' => "sessions#create"
get '/new' => "users#new"
get '/home' => "home#index"
get '/restaurant' => "restaurant#index"
get '/supplier' => "supplier#index"




  get 'sessions/destroy'
  get 'home/index'
  get 'supplier/index'
  get 'restaurant/index'
  get 'products/index'
  get '/pay' => "pages#pay"
  #get 'admin/index' => 'home#index'
  # get ''

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    #delete 'logout' => :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  resources :comments
  resources :posts do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    # has_many :comments, dependent: :destroy
    has_many :posts
	validates :name, presence: true, length: {minimum: 5}
	validates :body,  presence: true

    has_attached_file :image, styles: { large: "600x600>", medium: "300x300>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/discount.rb
class Discount < ApplicationRecord
	belongs_to :order_item
	belongs_to :order
	belongs_to :product

  	def percent_discount()
   	    self.discount/100
  	end

  	def price_discount
  		self.discount = percent_discount*TotalPrice || 0 
	end


end

app/models/order.rb
class Order < ApplicationRecord
    has_many:order_items
	has_many:product


	def subtotal
		order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}.sum
	end

	def method_name
		order_items.collect {|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity - (order_item.unit_price*order_item.quantity*order_item.product.discount)/100 : 0}.sum
	end

	def a
		order_items.collect {|order_item| order_item.valid? ? (order_item.product.supplyinstock - order_item.quantity) : 0}

	end

	# def discount
	# 	self[:discount] = subtotal *(subtotal-discount)*100
	# end
    def prices
    	order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}

    end

  	def percent_discount()
   	    self.discount/100
  	end

  	def price_discount
  		self.discount = percent_discount*TotalPrice || 0
	end


		private
		def set_subtotal
			self[:subtotal] = subtotal
		end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product


	before_save :set_unit_price
	before_save :set_total_price

	def unit_price
		if persisted?
			self[:unit_price]
		else
			product.price
		end
	end


	def TotalPrice
		unit_price * quantity
	end

		private

		def set_unit_price
			self[:unit_price] = unit_price
		end

		def set_total_price
			self[:TotalPrice] = quantity * set_unit_price
		end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	has_many:order_items
	has_many:discounts
	has_many:users
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb:"150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	# Product.order('id ASC').reorder('date DESC')


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :products

  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true, length: {maximum: 50},
                   format: {with: VALID_EMAIL_REGEX},
                   uniqueness: {case_sensitive: false}

 before_save {self.email=email.downcase}
 validates :password, length: {minimum: 6}
 has_secure_password

 has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb:"150x150#"}
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def index
  	@products = Product.all.order("date ASC")

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @comment = Comment.new
    end
    def index
        @comments = Comment.all
    end
    def create

        @comment = Comment.new(params[:comment].permit(:name, :body, :image))

        if @comment.save

            redirect_to @comment
        else
            render 'new'
        end
    end


    def show
        @comment = Comment.find(params[:id])
    end



    def edit

        @comment = Comment.find(params[:id])
    end

    def update
        @comment = Comment.find(params[:id])

        if @comment.update(params[:comment].permit(:name, :body, :image))

            redirect_to @comment
        else

            render 'edit'
        end
    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to comments_path
    end
    def current_order
     if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
     end
  end

    private
        def comment_params

            params.require(:comment).permit(:name, :body, :image)
        end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   @products = Product.all.order("date ASC").where(["title LIKE ?","%#{params[:search]}%"])
   	@order_item = current_order.order_items.new
  end


  	def current_order
		 if !session[:order_id].nil?
			Order.find(session[:order_id])
		else
			Order.new
		 end
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

		def current_order
		if !session[:order_id].nil?
			Order.find(session[:order_id])
		else
			Order.new
		end
	end
	
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div> <%= comment.name %> </div>
<div> <%= comment.body %> </div>

<div> <%= link_to 'Delete',[comment.post,comment], method: :delete data: { confirm: 'Are you sure' } %> </div>

app/views/comments/_form.html.erb
<%= form_for @comment, html: { multipart: true} do |f| %>
	<div class="form-group">
		<%= f.label :name, "Name" %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>


		<div class="form-group">
		<%= f.label :body, "Comment" %>
		<%= f.text_area :body, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image %>
	</div>


	<%= f.submit "Save", class: 'btn btn-success' %>

<% end %>

<%= form_for @comment, html: { multipart: true} do |f| %>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image %>
	</div>

	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing My Post</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<!-- <h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p> -->
<!DOCTYPE html>
<html>


<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-twothird">
    	<div class="col-md-6 col-md-offset-3">
	<table class="table" cellspacing="0" cellpadding="0" >
		<tbody>
			<% @comments.each do |comment| %>
			<tr>
			</tr>
				<tr>
					<td width="70%" > </td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>

					<td></td>
					<td></td>


        	<td><%= image_tag comment.image.url(:thumb) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div>
<table style="width:100%">
<%= link_to "New comment", new_comment_path %>

	<% @comments.each do |comment| %>
  <tr>
    <th><h1><%= comment.name %></h1></th>
  </tr>
  <tr>
    <td width="70%"><%= comment.body %> </td>

  </tr>

  <tr>
   
  </tr>
  <% end %>
</table>
</div>

      <p class="w3-text-grey">
         <div class="container">
    <div class="row-fluid">
    <div class="span4">
            <h2>Location and contact information</h2>
            <address>
                <strong>Carfour</strong><br>
                Mesiameer<br>
                Villagio Mall<br>
                Qatar<br>
                CT21 5SH<br>
                <abbr title="Phone">P:</abbr> 01234 567 890
            </address>
        </div>
        <div class="span8">
            <iframe width="50%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=q&source=s_q&hl=en&geocode=&q=15+Springfield+Way,+Hythe,+CT21+5SH&aq=t&sll=52.8382,-2.327815&sspn=8.047465,13.666992&ie=UTF8&hq=&hnear=15+Springfield+Way,+Hythe+CT21+5SH,+United+Kingdom&t=m&z=14&ll=51.077429,1.121722&output=embed"></iframe>
        </div>
        
        
    </div>
</div>
      </p>
    </div>

    <div class="w3-third w3-center">


    </div>
  </div>
</div>

<a href="/edit"><button class="button" style="vertical-align:middle, background-color: green "><span>Edit Page </span></button></a>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">
  <div class="w3-xlarge w3-padding-32">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
 </div>

</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

</style>
</head>
<body>



</body>
</html>

<style>
table, th. tr {border: none;}
</style>

app/views/comments/new.html.erb
<h1>New Post</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>
<br>
<br>
<a href="/comments"><button class="button" style="vertical-align:middle, background-color: green "><span>View Comments </span></button></a>

<style>
.button {
    background-color: #4CAF50; /* Green */
    width:100px;
    height:50px;
    color: white;
    border-radius: 8px;
    
}

.button:hover {
    background-color: #3e8e41;
}
  </style>

app/views/comments/show.html.erb
<div>Restaurant Name: <%= @comment.name %></div>
<div>
 Comment: <%= @comment.body %>
</div>
a: <%= @comment.image.url(:thumb) %>

<br>

<br>
<%=link_to "Edit", edit_comment_path(@comment) %>
<%=link_to "Delete", comment_path(@comment), method: :delete, data: { confirm: "Are you sure"} %>