config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products
  resources :order_items
  resource :carts, only: [:show]
  resources :posts
  get '/receipt' => "pages#receipt"
  #get '/supplier' => "pages#supplier"
  get '/about_us' => "pages#aboutus"
  get '/contact_us' => "pages#contactus"
  get '/logout' => "sessions#logout"

  root "admin#index"


  # get 'admin/index'
  post 'sessions/create'
  get 'users/new'

get '/create' => "sessions#create"
get '/new' => "users#new"
get '/home' => "home#index"
get '/restaurant' => "restaurant#index"
get '/supplier' => "supplier#index"




  get 'sessions/destroy'
  get 'home/index'
  get 'supplier/index'
  get 'restaurant/index'
  get 'products/index'
  get '/pay' => "pages#pay"
  #get 'admin/index' => 'home#index'
  # get ''

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    #delete 'logout' => :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  resources :comments
  resources :posts do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    # has_many :comments, dependent: :destroy
    has_many :posts
	validates :name, presence: true, length: {minimum: 5}
	validates :body,  presence: true

    has_attached_file :image, styles: { large: "600x600>", medium: "300x300>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/discount.rb
class Discount < ApplicationRecord
	belongs_to :order_item
	belongs_to :order
	belongs_to :product

  	def percent_discount()
   	    self.discount/100
  	end

  	def price_discount
  		self.discount = percent_discount*TotalPrice || 0 
	end


end

app/models/order.rb
class Order < ApplicationRecord
    has_many:order_items
	has_many:product


	def subtotal
		order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}.sum
	end

	def method_name
		order_items.collect {|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity - (order_item.unit_price*order_item.quantity*order_item.product.discount)/100 : 0}.sum
	end

	def a
		order_items.collect {|order_item| order_item.valid? ? (order_item.product.supplyinstock - order_item.quantity) : 0}

	end

	# def discount
	# 	self[:discount] = subtotal *(subtotal-discount)*100
	# end
    def prices
    	order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}

    end

  	def percent_discount()
   	    self.discount/100
  	end

  	def price_discount
  		self.discount = percent_discount*TotalPrice || 0
	end


		private
		def set_subtotal
			self[:subtotal] = subtotal
		end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product


	before_save :set_unit_price
	before_save :set_total_price

	def unit_price
		if persisted?
			self[:unit_price]
		else
			product.price
		end
	end


	def TotalPrice
		unit_price * quantity
	end

		private

		def set_unit_price
			self[:unit_price] = unit_price
		end

		def set_total_price
			self[:TotalPrice] = quantity * set_unit_price
		end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	has_many:order_items
	has_many:discounts
	has_many:users
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb:"150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	# Product.order('id ASC').reorder('date DESC')


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :products

  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true, length: {maximum: 50},
                   format: {with: VALID_EMAIL_REGEX},
                   uniqueness: {case_sensitive: false}

 before_save {self.email=email.downcase}
 validates :password, length: {minimum: 6}
 has_secure_password

 has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb:"150x150#"}
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def index
  	@products = Product.all.order("date ASC")

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   @products = Product.all.order("date ASC").where(["title LIKE ?","%#{params[:search]}%"])
   	@order_item = current_order.order_items.new
  end


  	def current_order
		 if !session[:order_id].nil?
			Order.find(session[:order_id])
		else
			Order.new
		 end
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

		def current_order
		if !session[:order_id].nil?
			Order.find(session[:order_id])
		else
			Order.new
		end
	end
	
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">

    <div class="row">

            <div class="col-md-12">
                <h1>Food Supplies for sale</h1>
                <div class="form-group">
                    <%= form_tag home_index_path, :method => 'get' do %>
                    <%= text_field_tag :search, params[:search], class: 'form-control', :placeholder=> 'Search By Product Title' %>
                    <br>
                    <%= submit_tag "Search", :class=> 'btn btn-primary' %>
                    <% end %>
                </div>
                <br>
            </div>
    </div>

  <!-- Navigation for products -->
<div class="products-navigation  push-down-15">
  <div class="row">
    <div class="col-xs-12  col-sm-8">
      <div class="products-navigation__title">
        <h3><span class="light">Buy</span> Food Today and Prevent Tomorrow's Waste </h3>
      </div>
    </div>
    <div class="col-xs-12  col-sm-4">
      <div class="products-navigation__arrows">
        <a href="#js--latest-products-carousel" data-slide="prev"><span class="glyphicon  glyphicon-chevron-left  glyphicon-circle  products-navigation__arrow"></span></a>&nbsp;
        <a href="#js--latest-products-carousel" data-slide="next"><span class="glyphicon  glyphicon-chevron-right  glyphicon-circle  products-navigation__arrow"></span></a>
      </div>
    </div>
  </div>
</div>


<!-- Products -->
<div id="js--latest-products-carousel" class="carousel slide" data-ride="carousel" data-interval="5000">
    <!-- Wrapper for slides -->
  <div class="carousel-inner">

    <div class="item active">
      <div class="row">


       <% @products.each do |product| %>

        <div class="col-xs-6 col-sm-3  js--isotope-target  js--cat-5" data-price="" data-rating="">
          <div class="products__single">
            <figure class="products__image">
              <a href="/products/<%= product.id %>">
                <%= image_tag product.image.url(:thumb), :class=> "product__image", :width=> "263", :height=>"334" %>
                <!-- <img alt="#" class="product__image" width="263" height="334" src="images/dummy/w263/15.jpg"> -->
              </a>
              <div class="product-overlay">
                <a class="product-overlay__more" href="single-product.html">
                  <span class="glyphicon glyphicon-search"></span>
                </a>
                <a class="product-overlay__cart" href="/products/<%= product.id %>">
                  +<span class="glyphicon glyphicon-shopping-cart"></span>
                </a>
                <div class="product-overlay__stock">
                  <span class="out-of-stock">&bull;</span> <span class="in-stock--text"> <%= product.unitsperpackage %>

                  </span>
                </div>
              </div>
            </figure>
            <div class="row">
              <div class="col-xs-9">
                <h5 class="products__title">
                  <a class="products__link  js--isotope-title" href="single-product.html"><%= product.title %></a>
                </h5>
              </div>
              <div class="col-xs-3">
                <div class="products__price">
                  <%= product.price - (product.price * product.discount)/100 %>
                </div>
              </div>
            </div>
            <div class="products__category">
              <%= product.productbrand %>

            </div>
             <div class="products__category">
              Production date: <%= product.productiondate %>
            </div>
              <div class="products__category">
              Expiration date: <%= product.date %>
            </div>
            <div class="products__category">
              Unit Per Package: <%= product.unitsperpackage %>
            </div>
            <div class="products__category">
              Units: <%= product.units %>
            </div>
                        <div class="products__category">
              Description: <%= product.productdiscription %>
            </div>
                                    <div class="products__category">
              Location: <%= product.location %>
            </div>
          </div>
        </div>

      <% end %>


      </div>
    </div>
  </div>
  </div>
  </div>